add some awesome speakers of the perl community
karlhorky/awesome-speakers pull request #114
Opened 2018-01-02 12:52 UTC by eiro

everyone was contacted by mail, irc, tweeter

2018-01-02 20:50 UTC, SaraVieira commented
I'm sorry , I can't merge because some of the speakers don't have their city :(

2018-01-03 19:01 UTC, Ovid requested changes
I'm no longer in Paris :)

2018-01-03 19:01 UTC, Ovid commented on README.md
> +https://twitter.com/OvidPerl
I now live in Cannes, France. I'd also add "Agile Training" and "Enterprise Testing" to that list.

2018-01-04 12:35 UTC, eiro commented
hello @SaraVieira,

now everyone has a town, please tell me if something is missing.

thanks

2018-01-04 14:04 UTC, SaraVieira commented
Hello !

Only saw this now but I'll get it merged :)

Just added a couple of pictures missing and fixed @Ovid  request 🙌

Thank you 🙏

2018-01-04 14:05 UTC, merged